version: '3.8'

services:
    webgl:
        container_name: unity_front
        depends_on:
            - py_back
        image: unity-webgl-demo
        build: .
        ports:
            - "5000:5000"
        stdin_open: true
        tty: true
    mongo:
        container_name: mongo_db
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - "27017:27017"
        volumes:
            - ./DB:/data/db
    py_back:
        container_name: py_backend
        depends_on:
            - mongo
        build: ./Backend
        ports:
            - "30000:30000"
        links:
            - mongo
        stdin_open: true 
        tty: true
